### ISSUE TITLE
Hey Sota, can you contribute my git-cheat-sheet for Japanese

### ISSUE THREAD

**Issue by arslanbilal** [sotayamashita/git-cheat-sheet#1]
I almost add everything my cheat sheet and you should look at the my repo. You can translate from English to Japanese. My repo address is: [git-cheat-sheet](https://github.com/arslanbilal/git-cheat-sheet)

**Comment by sotayamashita** [comment]
@arslanbilal I already have forked your repo into my organisation for translation which is named [jposts](https://github.com/jposts) and I am working it :construction:

**Comment by arslanbilal** [comment]
Perfect!
